### ISSUE TITLE
Tablero 3x3

### ISSUE THREAD

**Issue by damiancastelao** [Sr-fer/Tres-en-raya#1]
El tablero es de tres x tres, lo veo un poco raro... 2x4 y una casilla suelta cuando se estrecha.
¿Serías capaz de mantener siempre el 3x3?

**Comment by Sr-fer** [comment]
Hay algún ejemplo que me puedas ayudar?, no consigo hacerlo siempre 3x3

**Comment by damiancastelao** [comment]
¿Porque no usas grid?, en concreto grid-template-columns. Está en los apuntes.

**Comment by Sr-fer** [comment]
Este, era el problema que tenía en el anterior ejercicio, y después de mirar los apuntes sigo sin saber hacerlo
